package com.gychen.po;

import java.io.Serializable;

public class ReaderCard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_card.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_card.username
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_card.password
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_card.number
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_card
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_card.id
     *
     * @return the value of reader_card.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_card.id
     *
     * @param id the value for reader_card.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_card.username
     *
     * @return the value of reader_card.username
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_card.username
     *
     * @param username the value for reader_card.username
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_card.password
     *
     * @return the value of reader_card.password
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_card.password
     *
     * @param password the value for reader_card.password
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_card.number
     *
     * @return the value of reader_card.number
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_card.number
     *
     * @param number the value for reader_card.number
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}