package com.gychen.po;

import java.io.Serializable;
import java.util.Date;

public class ReaderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.name
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.sex
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.birthday
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.address
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.tel
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.email
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.card_id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private Integer cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_info
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.id
     *
     * @return the value of reader_info.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.id
     *
     * @param id the value for reader_info.id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.name
     *
     * @return the value of reader_info.name
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.name
     *
     * @param name the value for reader_info.name
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.sex
     *
     * @return the value of reader_info.sex
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.sex
     *
     * @param sex the value for reader_info.sex
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.birthday
     *
     * @return the value of reader_info.birthday
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.birthday
     *
     * @param birthday the value for reader_info.birthday
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.address
     *
     * @return the value of reader_info.address
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.address
     *
     * @param address the value for reader_info.address
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.tel
     *
     * @return the value of reader_info.tel
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.tel
     *
     * @param tel the value for reader_info.tel
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.email
     *
     * @return the value of reader_info.email
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.email
     *
     * @param email the value for reader_info.email
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.card_id
     *
     * @return the value of reader_info.card_id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.card_id
     *
     * @param cardId the value for reader_info.card_id
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }
}