package com.gychen.dao;

import com.gychen.po.LendList;

public interface LendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insert(LendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_list
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insertSelective(LendList record);
}