package com.gychen.dao;

import com.gychen.po.Notice;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insertSelective(Notice record);
}