package com.gychen.dao;

import com.gychen.po.ReaderCard;

public interface ReaderCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insert(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insertSelective(ReaderCard record);
}