package com.gychen.dao;

import com.gychen.po.ReaderInfo;

public interface ReaderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insert(ReaderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Mon Jul 20 13:54:44 CST 2020
     */
    int insertSelective(ReaderInfo record);
}